# Generated by Django 5.1.2 on 2024-10-25 20:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_uploadedfile_uploadedfolder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadedFolder',
            new_name='Folder',
        ),
    ]
