# Generated by Django 5.1.2 on 2024-10-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='trash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='trash',
            field=models.BooleanField(default=False),
        ),
    ]
