# Generated by Django 5.1.2 on 2024-10-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_folder_trash_uploadedfile_trash'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
